@startuml
title Game creation and initialization

start
:load GameConfiguration;
:create Game according to the GameConfiguration;


partition "Game initialization " {
	:init GameBoard;
	partition "GameBoard initialization " {
		:init Bag;
		:init CenterArea;
		:init Trash;
		:init Factories;
	}
	:init all players;
}
		
partition "Player initialization " {
	:init player board;	
	partition "PlayerBoard initialization " { 
		:init Wall;
		:init Floor;
		:init PatterArea;
	}
	:init stat;		
}

:start game;
end		
@enduml
