@startuml

Abstract class Tile {
	-Area currentArea
	+moveTo(int index, IndexedArea area)
	+moveTo(UnidexedArea area)
}


Tile <|-- SpecialTile
abstract class SpecialTile {
	+effect()
}

Tile <|-- ColoredTile
class ColoredTile {
	-Colors color
	+Colors getColor()
}

SpecialTile <|-- FirstTile
class FirstTile

Colors --* ColoredTile : "intern enum"
enum Colors {
	BLUE
	RED
	GREEN
	BLACK
	YELLOW
}


interface Area {
	+Tile removeTile(Tile tile)
	+int size()
	+boolean isEmpty()
	+boolean moveTilesTo(Area area)
}
Area <|-- UnidexedArea
interface UnidexedArea {
	+void add(Tile tile)
}

Area <|-- IndexedArea
interface IndexedArea {
	+void add(int index, Tile tile)
}

UnidexedArea <|.. OffSideArea
abstract class OffSideArea {
	-ArrayList<Tile> tiles
}

OffSideArea <|-- Bag
class Bag {
	+void refill(Trash trash)
}

OffSideArea <|-- Trash
class Trash {

}
IndexedArea <|.. CommonArea
abstract class CommonArea {
	ArrayList<Tile> tiles
}
CommonArea <|-- CenterArea
CommonArea <|-- Factorie
class Factorie {
	+ArrayList<Tile> createTiles(Bag bag)
}

abstract class PlayerArea

IndexedArea <|.. Wall
PlayerArea <|-- Wall
class Wall {
	-ArrayList<ArrayList<Tile>> tiles
}

UnidexedArea <|.. Floor
PlayerArea <|-- Floor
class Floor {
	-ArrayList<Tile> tiles
}

IndexedArea <|.. PatternArea
PlayerArea <|-- PatternArea
class PatternArea{
	-ArrayList<ArrayList<Tile>> tiles
}

abstract class Player {
	Stat stats
	PlayerBoard playerBoard
}

Stat  --* Player : "intern class"
class Stat {
	int totalScore
	int[] perRoundScore
	String name
	boolean isHuman
}

Player <|-- HumanPlayer
Player <|-- AIPlayer


class PlayerBoard
PlayerBoard --* Player : "intern class"


GameConfiguration -left-* Game : "intern class"
class GameConfiguration {
	-int nbOfPlayers
	-AIDifficulty
	+void saveTo(File f)
	+void loadFrom(File f)
}

Game --> Round : "observes"
class Game {
	-GameConfiguration config
	-ArrayList<Player> players
	-GameBoard board
	-LinkedList<Round> rounds
	-Round currentRound
	-Player winner
	-void loadConfig(GameConfiguration config)
	+void init(GameConfiguration config)
	+void play()
	+void shutdown()
}

Game --> GameBoard : "init"
GameBoard --* Game : "intern class"
class GameBoard {
	-ArrayList<PlayerBoard> playerBoards
	-Bag bag
	-Trash trash
	-Factorie[] factories
	-CenterArea center
	+init(GameConfiguration config)
}

Round --> PlayerBoard : "observes"
class PlayerBoard {
	-Wall playerWall
	-Floor playerFloor
	-PatternArea playerPatternArea
}

class Round {
	-LinkedList<Player> players
	+preparationPhase()
	+offerPhase()
	+decorationPhase()
}


App --> Game : "calls"
class App {
	+void main(String[] args)
}


@enduml
